### ISSUE TITLE
Poppy_fnc_logWarning - script error on loadout change

### ISSUE THREAD

**Issue by RaynorD** [7thCavalryGaming/cScripts#19]
Error is thrown anytime a loadout is selected.

2:17:11 Error in expression <eShowWarnings") == 1}) then {
Poppy_log pushBack ["Warning", _message];
};
};
>
 2:17:11   Error position: <pushBack ["Warning", _message];
};
};
>
 2:17:11   Error Type Number, expected Bool
 2:17:11 File C:\Users\...(mission)\cScripts\Loadouts\script\functions\main\fn_logWarning.sqf, line 7

**Comment by ColdEvul** [comment]
Report on the new repo this repo who led have bin shutdown already.  But left up to make sure all material was moved over to 7cav correctly. 

https://github.com/7Cav/cScripts

**Comment by RaynorD** [comment]
Wow, not sure how I got over here. Will make sure it's not because I have old code.
